export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_RESPONSE = 'DATA_RESPONSE';
export const FETCH_MALL_INDEX_SUCCESS = 'FETCH_MALL_INDEX_SUCCESS';
export const FETCH_MALL_INDEX_FAIL = 'FETCH_MALL_INDEX_FAIL';
export const FETCH_MALL_TABLIST_SUCCESS = 'FETCH_MALL_TABLIST_SUCCESS';